# Generated by Django 2.0.3 on 2018-03-23 18:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PagesLiked',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('accesstoken', models.CharField(max_length=300)),
                ('likedpages', models.CharField(max_length=600)),
            ],
        ),
    ]
