# Generated by Django 2.0.3 on 2018-03-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagesliked',
            name='uuid',
        ),
        migrations.AddField(
            model_name='pagesliked',
            name='id2',
            field=models.IntegerField(null=True),
        ),
    ]
