# Generated by Django 2.0.3 on 2018-03-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20180325_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesliked',
            name='pagename',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
